### ISSUE TITLE
Can you also target people only with their user id? 

### ISSUE THREAD

**Issue by Lucreativedesign** [milselarch/RCV-tele-bot#14]
Or do you need a @username?

**Comment by milselarch** [comment]
if you're talking the poll creation command, then yeah you can only specify the people who are allowed to vote for the poll you created via their telegram handles / usernames right now

**Comment by Lucreativedesign** [comment]
Ah okay, thanks. Yeah I have a couple of friends that don't have usernames, only user id's. So it doesn't work for me sadly!

**Comment by milselarch** [comment]
I didnt know that its possible for telegram users to not have usernames, so thanks for making me aware of this.  
I'm working on a overhaul of the database + codebase to support user self-registration in polls at the moment - will probably be including poll registration by user_id as well along the way as well.

**Comment by Lucreativedesign** [comment]
Great! Will see the update then!

**Comment by milselarch** [comment]
Heyo so just fyi theres like 3 ways for users without usernames to register for a poll now:
1. if you create a poll using the `/create_group_poll` command, the poll info message the bot spits out will also come with a button, and users (including those without usernames) can self-register for the poll by clicking on it.
2. alternatively you can explicitly specifiy the user_ids that are allowed to vote for the poll in the poll creation command itself e.g.    
    ```
    /create_poll #42022:
    poll title
    option 1
    option 2
    option 3
    ```
    will register the user with user_id 42022 for the poll, and they can vote from anywhere  
3. you can explicitly register a user by their id post-poll creation with the `/register_user_id` command  

Do note that polls are currently capped at 10 members per poll - I intend to eventually add some sort of subscription system that'll let people create polls with more people. If in the meantime you need to create polls with more members do feel free to let my know either here or on telegram.

**Comment by Lucreativedesign** [comment]
Thank you! Going to try it with my friends! :) We're with 18, so would be great if everyone could participate, but let me know if that's something that we can work out :)

**Comment by milselarch** [comment]
Sorry bout the late reply - I've been caught up with other stuff and I think it'll be getting around to the subscription system for quite a while, so I've raised the limit to 20 people per poll.

**Comment by Lucreativedesign** [comment]
Thank you!

Op ma 22 jul 2024 om 16:39 schreef Charles ***@***.***>:

**Comment by Lucreativedesign** [comment]
Hi there! Just a quick observation. With the /create_group_poll command inside a group chat, I have the impression that it's possible to vote multiple times as a user. Is this correct? :)

**Comment by milselarch** [comment]
heyo it should be impossible to vote multiple times because voters are registered for a poll based on their telegram id when they click the register button, so a user can vote, change their username and vote again and the new vote will be mapped back to the same user still.  

I guess someone could vote multiple times by creating multiple telegram accounts and casting votes using the different accounts, but there isn't any way to deal with that afaik.
